#!/usr/bin/env bash
# Script that installs Nginx server
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo chown -R ubuntu:ubuntu /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
