#!/usr/bin/env bash
# Adds IP address to /etc/hosts

cp /etc/hosts ~/hosts.new
echo "127.0.0.2     localhost" > ~/hosts.new
echo "8.8.8.8       facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
